<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="X-Komputer" name="com.websystique.testng.TestNGTimeOutExample" tests="2" failures="0" timestamp="8 Jan 2017 15:39:34 GMT" time="3.014" errors="1">
  <testcase name="testAdd" time="0.007" classname="com.websystique.testng.TestNGTimeOutExample"/>
  <testcase name="testSubtract" time="3.007" classname="com.websystique.testng.TestNGTimeOutExample">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method org.testng.internal.TestNGMethod.testSubtract() didn&#039;t finish within the time-out 3000">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testSubtract() didn't finish within the time-out 3000
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1160)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
]]>
    </error>
  </testcase> <!-- testSubtract -->
</testsuite> <!-- com.websystique.testng.TestNGTimeOutExample -->
